# Generated by Django 3.1.4 on 2020-12-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201228_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On Loan'), ('a', 'Available'), ('r', 'reserved'), ('b', 'borrowed')], default='m', help_text='Book Availability', max_length=1),
        ),
    ]
